### ISSUE TITLE
[Feature/Document]: 생년월일 필드 변경

### ISSUE THREAD

**Issue by dobbyyo** [Yunsik-Choi/Barter-API#12]
### Domain

User

### 어떠한 문서가 필요한가요?

회원가입 정보 생년월일 변경 
Ex)
birthday: "2022-01-05"
email: "do@as.com"
name: "asd"
password: "****" 
phoneNumber: "01000000000"
userId: "wqd"

### 고려사항

생년월일 Object로 나누지말고 하는것이 어떤가요??

### 할일목록

- [x] TODO

### Priority Label Setting

- [X] Yes! Priority Label 지정했습니다.

### Projects Card

- [X] Yes! 생성했습니다.

**Comment by Yunsik-Choi** [comment]
수정 완료
